language: generic
script:
 - bash ./kadai2.sh
 - bash ./kadai2.sh 20
 - bash ./kadai2.sh 12 15
 - bash ./kadai2.sh 12 15 | bash ./check_value.sh 12 15
 - bash ./kadai2.sh 12 20
 - bash ./kadai2.sh 12 20 | bash ./check_value.sh 12 20
 - bash ./kadai2.sh 15 20
 - bash ./kadai2.sh 15 20 | bash ./check_value.sh 15 20
 - bash ./kadai2.sh 12 20 DEBUG

